// <auto-generated />
using System;
using CampingRohani.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampingRohani.Migrations
{
    [DbContext(typeof(CampingRohaniContext))]
    [Migration("20260923155439_Migration230926_2")]
    partial class Migration230926_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CampingRohani.Model.Camp", b =>
                {
                    b.Property<int>("CampId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CampLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampTheme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParticipantCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CampId");

                    b.ToTable("Camps", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.ContactPerson", b =>
                {
                    b.Property<int>("ContactPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CampId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ContactPersonId");

                    b.HasIndex("CampId");

                    b.HasIndex("RegionId");

                    b.ToTable("ContactPersons", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.Participant", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Parish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ParticipantId");

                    b.HasIndex("RegionId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CampId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DirectoryProofImage")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CampId");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("CampId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RegionId");

                    b.HasIndex("CampId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.Registration", b =>
                {
                    b.Property<string>("RegistrationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CampId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("CampId");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.RegistrationContactPerson", b =>
                {
                    b.Property<int>("RegistrationContactPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContactPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RegistrationContactPersonId");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("RegistrationId", "ContactPersonId")
                        .IsUnique();

                    b.HasIndex("RegistrationId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("RegistrationContactPersons", (string)null);
                });

            modelBuilder.Entity("CampingRohani.Model.ContactPerson", b =>
                {
                    b.HasOne("CampingRohani.Model.Camp", null)
                        .WithMany("ContactPersons")
                        .HasForeignKey("CampId");

                    b.HasOne("CampingRohani.Model.Region", "Region")
                        .WithMany("ContactPersons")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CampingRohani.Model.Participant", b =>
                {
                    b.HasOne("CampingRohani.Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CampingRohani.Model.Payment", b =>
                {
                    b.HasOne("CampingRohani.Model.Camp", "Camp")
                        .WithMany()
                        .HasForeignKey("CampId");

                    b.HasOne("CampingRohani.Model.ContactPerson", "ContactPerson")
                        .WithMany("Payments")
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CampingRohani.Model.Registration", "Registration")
                        .WithOne("Payment")
                        .HasForeignKey("CampingRohani.Model.Payment", "RegistrationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Camp");

                    b.Navigation("ContactPerson");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CampingRohani.Model.Region", b =>
                {
                    b.HasOne("CampingRohani.Model.Camp", "Camp")
                        .WithMany("Regions")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("CampingRohani.Model.Registration", b =>
                {
                    b.HasOne("CampingRohani.Model.Camp", "Camp")
                        .WithMany("Registrations")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CampingRohani.Model.Participant", "Participant")
                        .WithOne("Registration")
                        .HasForeignKey("CampingRohani.Model.Registration", "ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Camp");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("CampingRohani.Model.RegistrationContactPerson", b =>
                {
                    b.HasOne("CampingRohani.Model.ContactPerson", "ContactPerson")
                        .WithMany("AssignedRegistrations")
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampingRohani.Model.Registration", "Registration")
                        .WithMany("ContactPersonAssignments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContactPerson");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CampingRohani.Model.Camp", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("Regions");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("CampingRohani.Model.ContactPerson", b =>
                {
                    b.Navigation("AssignedRegistrations");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CampingRohani.Model.Participant", b =>
                {
                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CampingRohani.Model.Region", b =>
                {
                    b.Navigation("ContactPersons");
                });

            modelBuilder.Entity("CampingRohani.Model.Registration", b =>
                {
                    b.Navigation("ContactPersonAssignments");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
